### ISSUE TITLE
YOO

### ISSUE THREAD

**Issue by Tuvqlu** [SandhyR/TheBridge#1]
IF THIS WORKS BRO BEST PLUGIN EVER

**Comment by SandhyR** [comment]
This plugin is not finished yet, I will finish it soon

**Comment by Tuvqlu** [comment]
How long until, this seems amazing lol

**Comment by Ju999** [comment]
Arena doesn't start yet :(

**Comment by Tuvqlu** [comment]
When finish crashes atm

**Comment by SandhyR** [comment]
If I'm not busy

**Comment by Tuvqlu** [comment]
K
