### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RazzyGP** [SandhyR/TheBridge#10]
![image](https://user-images.githubusercontent.com/91236261/159787870-870180f7-a4e8-425e-a076-92db1ed8bdfa.png) can u help?

**Comment by SandhyR** [comment]
Download plugin from poggit

**Comment by SandhyR** [comment]
https://poggit.pmmp.io/ci/SandhyR/TheBridge/TheBridge

**Comment by RazzyGP** [comment]
Can you send me your discord? I'm finding several possible bugs

**Comment by SandhyR** [comment]
SandhyR#2901

**Comment by RandomNonDev** [comment]
@RazzyGP 
download a plugin called "DeVirion", put it in your plugin folder then make a new folder named "virions" get the virion Commando at "https://poggit.pmmp.io/ci/CortexPE/Commando/Commando", dont put it in plugin folder after downloading put it in virions

you can do the same with ScoreFactory if you also getting an error of that one!
