### ISSUE TITLE
EPIC

### ISSUE THREAD

**Issue by Tuvqlu** [SandhyR/TheBridge#2]
Hey! This plugin is actually insane: only one problem: You can not edit scoreboard or config! That is all! create a config file, and wow!

This is insane :D

Some Other Bugs and Suggestions:

- Make it spawn you at first in the world spawn point not your side
- add cosmetics
- Leave item doesnt work
- after you score once, the cages dont release yo u
-  quit command does not work
- When leaving:
case "RUNNING":
                foreach ($this->players as $player){
                    if($this->cage) {
                        $player->sendTitle("", TextFormat::GRAY . "Cages will open in " . TextFormat::GREEN . $this->cagecountdown);
                        $player->getWorld()->addSound($player->getPosition(), new PopSound());
                    }
                    ScoreFactory::setObjective($player, TextFormat::YELLOW . TextFormat::BOLD . "THE BRIDGE");
                    ScoreFactory::setScoreLine($player, 1, TextFormat::WHITE . "Time left: " . TextFormat::GREEN . Utils::intToString($this->timer));
                    ScoreFactory::setScoreLine($player, 2, TextFormat::RED . TextFormat::BOLD . "[R]" . TextFormat::RESET . Utils::intToPoint($this->playerinfo[array_search("red", $this->teams)]["goals"]));
                    ScoreFactory::setScoreLine($player, 3, TextFormat::BLUE . TextFormat::BOLD . "[B]" . TextFormat::RESET . Utils::intToPoint($this->playerinfo[array_search("blue", $this->teams)]["goals"]));
                    ScoreFactory::setScoreLine($player, 4, TextFormat::WHITE . "Kills: " . TextFormat::GREEN . $this->playerinfo[strtolower($player->getName())]["kills"]);
                    ScoreFactory::setScoreLine($player, 5, TextFormat::WHITE . "Goals: " . TextFormat::GREEN . $this->playerinfo[strtolower($player->getName())]["goals"]);
                    ScoreFactory::setScoreLine($player, 6, TextFormat::WHITE . "Map: " . $this->arenainfo["arenaname"]);
                    ScoreFactory::setScoreLine($player, 7, TextFormat::WHITE . "Mode: Solo");
                    ScoreFactory::setScoreLine($player, 8, " ");
                    ScoreFactory::setScoreLine($player, 9, TextFormat::YELLOW . "yourservername.com");
                    ScoreFactory::sendObjective($player);
                    ScoreFactory::sendLines($player);
                }
                if ($this->cagecountdown <= 0) {

**Comment by ItsToxicGG** [comment]
actually very good idea.
